version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:12.13
    working_directory: ~/repository

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  release:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Setup Environment
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            echo "export GH_TOKEN=$GH_TOKEN" >> $BASH_ENV
      - run:
          name: Setup github
          command: |
            git config --global user.email $GITHUB_EMAIL
            git config --global user.name $GITHUB_USER

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: git diff packages/lumos/bin/lumos
      - run: yarn run release
  release-alpha:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Setup Environment
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            echo "export GH_TOKEN=$GH_TOKEN" >> $BASH_ENV
      - run:
          name: Setup github
          command: |
            git config --global user.email $GITHUB_EMAIL
            git config --global user.name $GITHUB_USER

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn setup
      - run: yarn run release-alpha
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
      - release-alpha:
          requires:
            - build
          filters:
            branches:
              ignore: master
