name: Pull request check

on:
  pull_request:
    branches:
      - master

jobs:
  pull_request_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install --frozen-lockfile --ignore-engines
      - run: yarn beemo run-script pull-request-checks-github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
