name: Test
on: push
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
      fail-fast: true
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup
        run: yarn install --frozen-lockfile --ignore-engines
      - name: Prepare
        run: yarn run setup
      - name: Run TypeScript
        run: yarn run build
      - name: Run Jest
        run: yarn run jest
      - name: Run ESLint
        run: yarn run eslint
